# Generated by Django 5.1 on 2026-02-21 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('direct_messages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='is_accepted',
            field=models.BooleanField(default=False),
        ),
    ]
