# Generated by Django 5.1 on 2026-02-17 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_profile_handle'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='handle',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
