# Generated by Django 5.1 on 2026-02-17 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_profile_handle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='handle',
        ),
    ]
